# Generated by Django 5.2.7 on 2025-11-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0004_workouttips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttips',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
