# Generated by Django 5.2.7 on 2025-12-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0005_alter_workouttips_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttips',
            name='duration',
            field=models.CharField(blank=True, null=True),
        ),
    ]
