# Generated by Django 5.2.7 on 2025-12-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0006_alter_workouttips_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='medicalcondition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
