# Generated by Django 5.2.7 on 2025-12-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0008_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
