# Generated by Django 5.2.7 on 2025-12-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0010_alter_feedback_options_alter_feedback_website_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='fitnessgoal',
            field=models.CharField(blank=True, choices=[('musclebuilding', 'musclebuilding'), ('weightloss', 'weightloss'), ('weightgain', 'weightgain'), ('bodybuilding', 'bodybuilding'), ('fitness', 'fitness')], max_length=30, null=True),
        ),
    ]
