# Generated by Django 5.2.7 on 2025-12-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0011_register_fitnessgoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='medicalcondition',
        ),
    ]
