# Generated by Django 5.2.7 on 2025-12-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0012_remove_register_medicalcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('current_weight', models.CharField(blank=True, max_length=300, null=True)),
                ('current_height', models.CharField(blank=True, max_length=300, null=True)),
                ('workout_status', models.CharField(blank=True, max_length=100, null=True)),
                ('current_fat', models.CharField(blank=True, max_length=300, null=True)),
                ('current_cholestrole', models.CharField(blank=True, max_length=300, null=True)),
                ('current_suger', models.CharField(blank=True, max_length=300, null=True)),
                ('ai_suggestions', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_name', to='aifitnesscoach_app.register')),
            ],
        ),
    ]
