# Generated by Django 5.2.7 on 2025-12-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0013_health_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_condition',
            name='injuries',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
