# Generated by Django 5.2.7 on 2025-12-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0014_health_condition_injuries'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='health_condition',
            name='allow_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='health_condition',
            name='animations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='health_condition',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='health_condition',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
