# Generated by Django 5.2.7 on 2025-12-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0015_adminsettings_health_condition_allow_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_condition',
            name='allow_registration',
        ),
        migrations.RemoveField(
            model_name='health_condition',
            name='animations',
        ),
        migrations.RemoveField(
            model_name='health_condition',
            name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='health_condition',
            name='maintenance_mode',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='allow_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='animations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
