# Generated by Django 5.2.7 on 2025-12-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0016_remove_health_condition_allow_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_condition',
            name='ai_suggestions',
            field=models.CharField(blank=True, null=True),
        ),
    ]
