# Generated by Django 5.2.7 on 2025-12-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0017_alter_health_condition_ai_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_condition',
            name='ai_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
