# Generated by Django 5.2.7 on 2025-12-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0018_alter_health_condition_ai_suggestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health_condition',
            old_name='workout_status',
            new_name='fitness_goal',
        ),
    ]
