# Generated by Django 5.2.7 on 2025-12-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0019_rename_workout_status_health_condition_fitness_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='loggedin_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
