# Generated by Django 5.2.7 on 2025-12-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0020_register_loggedin_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_condition',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
