# Generated by Django 5.2.7 on 2026-01-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0022_subscriptionplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminSettings',
        ),
        migrations.RenameField(
            model_name='health_condition',
            old_name='name',
            new_name='user',
        ),
    ]
