# Generated by Django 5.2.7 on 2026-01-19 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0024_subscriptionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aifitnesscoach_app.subscriptionplan'),
        ),
    ]
