# Generated by Django 5.2.7 on 2026-01-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0025_register_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionorder',
            name='created_at',
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
