# Generated by Django 5.2.7 on 2026-01-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0026_remove_subscriptionorder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in days', null=True),
        ),
    ]
