# Generated by Django 5.2.7 on 2026-01-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0027_alter_subscriptionplan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorder',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
