# Generated by Django 5.1.2 on 2026-02-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0028_subscriptionorder_is_trial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workouts/')),
                ('workout_name', models.CharField(blank=True, max_length=100, null=True)),
                ('posture_status', models.CharField(blank=True, choices=[('CORRECT', 'Correct'), ('INCORRECT', 'Incorrect')], max_length=10, null=True)),
                ('confidence_score', models.IntegerField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, max_length=100, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.AlterField(
            model_name='health_condition',
            name='ai_suggestions',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workouttips',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
