# Generated by Django 5.2.7 on 2026-02-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0029_workoutanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutanalysis',
            name='rep_count',
            field=models.IntegerField(default=0),
        ),
    ]
