# Generated by Django 5.2.7 on 2026-02-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0030_workoutanalysis_rep_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_analyses', to='aifitnesscoach_app.register'),
        ),
    ]
