# Generated by Django 5.2.7 on 2026-02-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifitnesscoach_app', '0031_workoutanalysis_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutanalysis',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutanalysis',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
